Update securitycodescan.yml
Signed-off-by: kimbyungkwon <120926381+davidkims@users.noreply.github.com>

diff --git a/.github/workflows/securitycodescan.yml b/.github/workflows/securitycodescan.yml
--- a/.github/workflows/securitycodescan.yml
+++ b/.github/workflows/securitycodescan.yml
@@ -21,6 +21,10 @@ jobs:
           mkdir Project/swiftapp
           echo "" > Project/logs/failures.log
           dotnet new console --output Project/src --framework net6.0
+          if (!(Test-Path -Path "Project/src/Project.csproj")) {
+            echo "❌ Project.csproj not created." | Out-File -Append Project/logs/failures.log
+            exit 1
+          }
         shell: pwsh
 
       - name: ⚙️ Setup .NET
